Exclusions777
AdguardTeam/HttpsExclusions pull request #384
Opened 2021-02-20 12:49 UTC by Chinaski1

https://github.com/AdguardTeam/AdguardForAndroid/issues/3756

2021-02-24 08:59 UTC, admitrevskiy requested changes

2021-02-24 08:59 UTC, admitrevskiy commented on exclusions/android.txt
> +posteitalianespa.sc.omtrdc.net.$app=posteitaliane.posteapp.appbpol
Точка лишняя после `net`

2021-02-24 08:59 UTC, admitrevskiy commented on exclusions/android.txt
> +
Переносы лишние

2021-02-24 09:06 UTC, admitrevskiy approved these changes

2021-02-24 09:07 UTC, merged

2022-03-28 20:09 UTC, hanoshita commented
Request add to exclusion app: https://play.google.com/store/apps/details?id=posteitaliane.posteapp.appposteid