Add Veridian & Transamerica
AdguardTeam/HttpsExclusions pull request #584
Opened 2024-03-18 12:54 UTC by piquark6046

Fix https://github.com/AdguardTeam/HttpsExclusions/issues/583

2024-03-18 14:20 UTC, zloyden commented on exclusions/banks.txt
> +secure2.transamerica.com
As I see, they also use `secure.transamerica.com`. I guess we can add it or just the whole domain.

2024-03-18 15:57 UTC, Alex-302 commented on exclusions/banks.txt
> +secure2.transamerica.com
Is it really a bank or similar service?

2024-03-26 14:24 UTC, Alex-302 requested changes

2024-03-26 14:24 UTC, Alex-302 commented on exclusions/banks.txt
> +secure2.transamerica.com
@piquark6046 Let's apply to `transamerica.com`.

2024-03-27 14:14 UTC, zloyden requested changes

2024-03-27 14:14 UTC, zloyden commented on exclusions/banks.txt
> +participant.transamerica.com
I assume you can remove it safely since we have `transamerica.com`.

2024-03-27 18:10 UTC, Alex-302 commented on exclusions/banks.txt
> +participant.transamerica.com
```suggestion
```

2024-03-28 06:45 UTC, zloyden approved these changes

2024-03-28 11:03 UTC, Alex-302 approved these changes

2024-03-28 11:03 UTC, merged