Enhance Exclusions: Add Bangladeshi Banks, Financial Institutions, Freelancer.com, and Termius.com
AdguardTeam/HttpsExclusions pull request #600
Opened 2024-07-31 22:14 UTC by sumonst21

Add Bangladeshi banks and financial institutions to the exclusions list. Also, add freelancer.com and termius.com to the exclusions list.

2024-08-01 05:36 UTC, piquark6046 requested changes
Please attach some references like Wikipedia to describe about them.

2024-08-22 04:10 UTC, piquark6046 requested changes

2024-08-22 04:10 UTC, piquark6046 commented on exclusions/banks.txt
> +// banks, financial institutions, payment systems, MFS (mobile financial services), etc from Bangladesh. referances: https://www.bb.org.bd/en/index.php/links/links/9, https://www.bb.org.bd/en/index.p
Adding this comment is not necessary. Please remove it and reorder by alphabet order.

2024-08-22 06:59 UTC, sumonst21 commented on exclusions/banks.txt
> +// banks, financial institutions, payment systems, MFS (mobile financial services), etc from Bangladesh. referances: https://www.bb.org.bd/en/index.php/links/links/9, https://www.bb.org.bd/en/index.p
Done

2024-08-22 07:01 UTC, sumonst21 commented on exclusions/banks.txt
> +// banks, financial institutions, payment systems, MFS (mobile financial services), etc from Bangladesh. referances: https://www.bb.org.bd/en/index.php/links/links/9, https://www.bb.org.bd/en/index.p
let me know if you want me to re-order the sensitive.txt as well. @piquark6046

2024-08-22 07:14 UTC, piquark6046 requested changes

2024-08-22 07:14 UTC, piquark6046 commented on exclusions/banks.txt
> -//
Please revert this change.

2024-08-22 07:19 UTC, sumonst21 commented on exclusions/banks.txt
> -//
done

2024-08-22 07:24 UTC, piquark6046 approved these changes

2024-08-22 07:26 UTC, piquark6046 requested changes

2024-08-22 07:26 UTC, piquark6046 commented on exclusions/sensitive.txt
> +freelancer.co.id
As far as i know, if there is a domain named as `example.com`, all subdomains of it will be excluded from HTTPS filtering.
Please remove the duplicated domains.

2024-08-22 07:28 UTC, sumonst21 commented on exclusions/sensitive.txt
> +freelancer.co.id
Done

2024-08-22 07:30 UTC, piquark6046 approved these changes

2024-08-22 07:30 UTC, merged